"""create solicitudes table

Revision ID: 1fdf71aaba95
Revises: 8f9a7511ee0a
Create Date: 2026-01-15 14:50:46.256918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdf71aaba95'
down_revision = '8f9a7511ee0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['etapas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['estados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_area_id'), 'solicitudes', ['area_id'], unique=False)
    op.create_index('ix_solicitudes_created_at', 'solicitudes', ['created_at'], unique=False)
    op.create_index(op.f('ix_solicitudes_created_by_user_id'), 'solicitudes', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_id'), 'solicitudes', ['id'], unique=False)
    op.create_index(op.f('ix_solicitudes_stage_id'), 'solicitudes', ['stage_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_status_id'), 'solicitudes', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_status_id'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_stage_id'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_id'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_created_by_user_id'), table_name='solicitudes')
    op.drop_index('ix_solicitudes_created_at', table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_area_id'), table_name='solicitudes')
    op.drop_table('solicitudes')
    # ### end Alembic commands ###
