"""create areas table

Revision ID: 411ce0579f1f
Revises: 7bd9b2a18e15
Create Date: 2026-01-14 08:28:10.109956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411ce0579f1f'
down_revision = '7bd9b2a18e15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_index(op.f('ix_areas_nombre'), 'areas', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_areas_nombre'), table_name='areas')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
