"""create etapas table

Revision ID: 62bc3988afc2
Revises: 83a118020fa3
Create Date: 2026-01-14 10:55:29.647184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bc3988afc2'
down_revision = '83a118020fa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapas',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('approval_mode', sa.Enum('ANY', 'ALL', name='approvalmode'), server_default='ANY', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'code', name='uq_etapas_area_code'),
    sa.UniqueConstraint('area_id', 'order', name='uq_etapas_area_order')
    )
    op.create_index('ix_etapas_area_code', 'etapas', ['area_id', 'code'], unique=False)
    op.create_index(op.f('ix_etapas_area_id'), 'etapas', ['area_id'], unique=False)
    op.create_index('ix_etapas_area_order', 'etapas', ['area_id', 'order'], unique=False)
    op.create_index(op.f('ix_etapas_id'), 'etapas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etapas_id'), table_name='etapas')
    op.drop_index('ix_etapas_area_order', table_name='etapas')
    op.drop_index(op.f('ix_etapas_area_id'), table_name='etapas')
    op.drop_index('ix_etapas_area_code', table_name='etapas')
    op.drop_table('etapas')
    # ### end Alembic commands ###
