"""create solicitud_eventos table

Revision ID: 6392fce3515a
Revises: 9c31b7133694
Create Date: 2026-01-15 15:09:39.389827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6392fce3515a'
down_revision = '9c31b7133694'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_eventos',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'COMMENTED', 'STAGE_CHANGED', name='eventaction'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['etapas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['estados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_eventos_actor_user_id'), 'solicitud_eventos', ['actor_user_id'], unique=False)
    op.create_index('ix_solicitud_eventos_created_at', 'solicitud_eventos', ['created_at'], unique=False)
    op.create_index(op.f('ix_solicitud_eventos_id'), 'solicitud_eventos', ['id'], unique=False)
    op.create_index('ix_solicitud_eventos_solicitud_id', 'solicitud_eventos', ['solicitud_id'], unique=False)
    op.create_index('ix_solicitud_eventos_stage_id', 'solicitud_eventos', ['stage_id'], unique=False)
    op.create_index('ix_solicitud_eventos_status_id', 'solicitud_eventos', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_solicitud_eventos_status_id', table_name='solicitud_eventos')
    op.drop_index('ix_solicitud_eventos_stage_id', table_name='solicitud_eventos')
    op.drop_index('ix_solicitud_eventos_solicitud_id', table_name='solicitud_eventos')
    op.drop_index(op.f('ix_solicitud_eventos_id'), table_name='solicitud_eventos')
    op.drop_index('ix_solicitud_eventos_created_at', table_name='solicitud_eventos')
    op.drop_index(op.f('ix_solicitud_eventos_actor_user_id'), table_name='solicitud_eventos')
    op.drop_table('solicitud_eventos')
    # ### end Alembic commands ###
