"""create estados table

Revision ID: 83a118020fa3
Revises: 2ce4a15ac91c
Create Date: 2026-01-14 10:40:49.466899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a118020fa3'
down_revision = '2ce4a15ac91c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_estados_code')
    )
    op.create_index(op.f('ix_estados_code'), 'estados', ['code'], unique=True)
    op.create_index(op.f('ix_estados_id'), 'estados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estados_id'), table_name='estados')
    op.drop_index(op.f('ix_estados_code'), table_name='estados')
    op.drop_table('estados')
    # ### end Alembic commands ###
