"""create etapa_aprobadores table

Revision ID: 8f9a7511ee0a
Revises: 62bc3988afc2
Create Date: 2026-01-15 14:42:39.723862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9a7511ee0a'
down_revision = '62bc3988afc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapa_aprobadores',
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etapa_id', 'user_id', name='uq_etapa_aprobadores_etapa_user')
    )
    op.create_index(op.f('ix_etapa_aprobadores_etapa_id'), 'etapa_aprobadores', ['etapa_id'], unique=False)
    op.create_index('ix_etapa_aprobadores_etapa_user', 'etapa_aprobadores', ['etapa_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_etapa_aprobadores_id'), 'etapa_aprobadores', ['id'], unique=False)
    op.create_index(op.f('ix_etapa_aprobadores_user_id'), 'etapa_aprobadores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etapa_aprobadores_user_id'), table_name='etapa_aprobadores')
    op.drop_index(op.f('ix_etapa_aprobadores_id'), table_name='etapa_aprobadores')
    op.drop_index('ix_etapa_aprobadores_etapa_user', table_name='etapa_aprobadores')
    op.drop_index(op.f('ix_etapa_aprobadores_etapa_id'), table_name='etapa_aprobadores')
    op.drop_table('etapa_aprobadores')
    # ### end Alembic commands ###
