"""create solicitud_files table

Revision ID: 9c31b7133694
Revises: 1fdf71aaba95
Create Date: 2026-01-15 14:59:09.903312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c31b7133694'
down_revision = '1fdf71aaba95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_files',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_solicitud_files_size_bytes_positive'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_id', 'storage_path', name='uq_solicitud_files_solicitud_storage')
    )
    op.create_index('ix_solicitud_files_created_at', 'solicitud_files', ['created_at'], unique=False)
    op.create_index('ix_solicitud_files_doc_type', 'solicitud_files', ['doc_type'], unique=False)
    op.create_index(op.f('ix_solicitud_files_id'), 'solicitud_files', ['id'], unique=False)
    op.create_index('ix_solicitud_files_solicitud_id', 'solicitud_files', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_solicitud_files_solicitud_id', table_name='solicitud_files')
    op.drop_index(op.f('ix_solicitud_files_id'), table_name='solicitud_files')
    op.drop_index('ix_solicitud_files_doc_type', table_name='solicitud_files')
    op.drop_index('ix_solicitud_files_created_at', table_name='solicitud_files')
    op.drop_table('solicitud_files')
    # ### end Alembic commands ###
