"""add_must_change_password_to_usuarios

Revision ID: b03a6c09e7d3
Revises: c5b748c2e7f4
Create Date: 2026-02-19 10:45:16.313126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03a6c09e7d3'
down_revision = 'c5b748c2e7f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'must_change_password')
    # ### end Alembic commands ###
