"""add_is_final_stage_to_etapas

Revision ID: bdc9cdaf107f
Revises: c1d2e3f4a5b6
Create Date: 2026-04-07 16:51:34.128960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc9cdaf107f'
down_revision = 'c1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_approval_tokens_token'), 'approval_tokens', type_='unique')
    op.add_column('etapas', sa.Column('is_final_stage', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_iniciativas_status'), table_name='iniciativas')
    op.create_index(op.f('ix_iniciativas_approved_by_gg_user_id'), 'iniciativas', ['approved_by_gg_user_id'], unique=False)
    op.create_index(op.f('ix_iniciativas_solicitud_id'), 'iniciativas', ['solicitud_id'], unique=False)
    op.create_index(op.f('ix_iniciativas_solicitud_innovacion_id'), 'iniciativas', ['solicitud_innovacion_id'], unique=False)
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.create_index(op.f('ix_notificaciones_iniciativa_id'), 'notificaciones', ['iniciativa_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_solicitud_id'), 'notificaciones', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificaciones_solicitud_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_iniciativa_id'), table_name='notificaciones')
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.drop_index(op.f('ix_iniciativas_solicitud_innovacion_id'), table_name='iniciativas')
    op.drop_index(op.f('ix_iniciativas_solicitud_id'), table_name='iniciativas')
    op.drop_index(op.f('ix_iniciativas_approved_by_gg_user_id'), table_name='iniciativas')
    op.create_index(op.f('ix_iniciativas_status'), 'iniciativas', ['status'], unique=False)
    op.drop_column('etapas', 'is_final_stage')
    op.create_unique_constraint(op.f('uq_approval_tokens_token'), 'approval_tokens', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
